# EmbedMetalKernels.cmake
#
# Embeds .metal source files into the binary as C++ raw-string-literal
# externs.  MTLDevice newLibraryWithSource: compiles them at runtime, so the
# build never invokes `xcrun metal` and never emits a .metallib.  Mirrors
# EmbedCudaKernels.cmake exactly; only the file extension and namespace
# differ.
#
# Usage:
#   embed_metal_kernels(TARGET <target> KERNELS <a.metal> <b.metal> ...)
# Generates ${CMAKE_CURRENT_BINARY_DIR}/mtl_kernels_generated.cpp with
# `extern const char *<name>_src;` and `<name>_name;` per kernel, in the
# mtl_kernels namespace declared in include/mtl_peak.h.
#
# Defines CLPEAK_MTL_HAS_<NAME> on the target so per-kernel host code can
# be conditionally compiled.

function(embed_metal_kernels)
  cmake_parse_arguments(EM "" "TARGET" "KERNELS" ${ARGN})

  set(GEN_CPP "${CMAKE_CURRENT_BINARY_DIR}/mtl_kernels_generated.cpp")
  set(CPP_CONTENT "// Auto-generated by EmbedMetalKernels.cmake.  Do not edit.\n")
  string(APPEND CPP_CONTENT "namespace mtl_kernels {\n\n")

  foreach(KERNEL ${EM_KERNELS})
    if(NOT EXISTS "${KERNEL}")
      message(FATAL_ERROR "embed_metal_kernels: source not found: ${KERNEL}")
    endif()
    get_filename_component(KERNEL_NAME ${KERNEL} NAME_WE)
    set_property(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
      APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${KERNEL}")

    file(READ "${KERNEL}" KSRC)
    set(DELIM "CLPEAK_MDELIM")
    string(APPEND CPP_CONTENT "// from ${KERNEL_NAME}.metal\n")
    # No `extern` keyword: `const char *X = ...` has external linkage at
    # namespace scope (only top-level const objects default to internal),
    # so `extern T x = init;` triggers -Wextern-initializer.
    string(APPEND CPP_CONTENT "const char *${KERNEL_NAME}_name = \"${KERNEL_NAME}.metal\";\n")
    string(APPEND CPP_CONTENT "const char *${KERNEL_NAME}_src = R\"${DELIM}(\n")
    string(APPEND CPP_CONTENT "${KSRC}")
    string(APPEND CPP_CONTENT ")${DELIM}\";\n\n")

    string(TOUPPER "${KERNEL_NAME}" KU)
    target_compile_definitions(${EM_TARGET} PRIVATE CLPEAK_MTL_HAS_${KU})
  endforeach()

  string(APPEND CPP_CONTENT "} // namespace mtl_kernels\n")
  file(WRITE "${GEN_CPP}" "${CPP_CONTENT}")
  target_sources(${EM_TARGET} PRIVATE "${GEN_CPP}")
endfunction()
