#ifndef ROCM_PEAK_H
#define ROCM_PEAK_H

#ifdef ENABLE_ROCM

#include <hip/hip_runtime.h>
#include <common/common.h>
#include <common/inventory.h>
#include <common/logger.h>
#include <common/peak.h>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

struct CliOptions;

// One embedded kernel: a precompiled HIP code-object bundle (hipcc --genco at
// build time) plus its file stem for diagnostics.  Defined fully at the bottom
// of this header; forward-declared so the descriptor structs can point at it.
namespace rocm_kernels { struct Blob; }

struct rocm_device_info_t {
  std::string deviceName;
  std::string driverVersion;
  std::string runtimeVersion;
  std::string archName;

  DeviceType deviceType = DeviceType::Unknown;

  int numCUs = 0;
  int maxThreadsPerBlock = 0;
  uint64_t totalGlobalMem = 0;
  int clockRateKHz = 0;
  int warpSize = 0;

  bool fp16Supported = false;
  bool bf16Supported = false;
  bool rocwmmaSupported = false;
};

class RocmDevice
{
public:
  int deviceIndex;
  hipStream_t stream;
  rocm_device_info_t info;

  RocmDevice();
  ~RocmDevice();

  bool init(int devIndex);
  void cleanup();

  // Load a precompiled code-object bundle into a module (the HIP runtime picks
  // the slice matching this device's gfx arch), then resolve a named kernel.
  // Caches by blob-data pointer; needs only the HIP runtime at run time -- no
  // HIPRTC, no ROCm headers.  A missing slice (kernel not built for this arch)
  // returns false; the detail is emitted via CLPEAK_VLOG so it only shows under
  // --verbose and never disturbs the default result output.
  bool getKernel(const rocm_kernels::Blob &blob,
                 const char *kernelName, hipFunction_t &fn);

private:
  std::unordered_map<const void *, hipModule_t> moduleCache;
};

struct rocm_compute_variant_t
{
  const char *label;
  const char *kernelName;
  const rocm_kernels::Blob *blob;
};

struct rocm_compute_desc_t
{
  const char *title;
  const char *resultTag;
  const char *unit;
  double      unitDivider;

  const char *metricLabel;
  const char *kernelName;
  const rocm_kernels::Blob *blob;

  const rocm_compute_variant_t *variants;
  uint32_t numVariants;

  uint32_t workPerWI;
  uint32_t elemSize;
  uint32_t blockSize;
  uint32_t outElemsPerBlock;

  const void *scalarArg;
  uint32_t    scalarSize;

  bool        skip;
  const char *skipMsg;
};

class RocmPeak : public Peak
{
public:
  std::vector<int> deviceIndices;  // empty = run all

  RocmPeak();
  ~RocmPeak();

  void applyOptions(const CliOptions &opts) override;
  int runAll() override;

  static BackendInventory enumerate();
  static void printInventory(const BackendInventory &inv, std::ostream &os);

  int runComputeSP(RocmDevice &dev, benchmark_config_t &cfg);
  int runComputeHP(RocmDevice &dev, benchmark_config_t &cfg);
  int runComputeDP(RocmDevice &dev, benchmark_config_t &cfg);
  int runComputeMP(RocmDevice &dev, benchmark_config_t &cfg);
  int runComputeBF16(RocmDevice &dev, benchmark_config_t &cfg);
  int runComputeInt32(RocmDevice &dev, benchmark_config_t &cfg);
  int runComputeInt8DP(RocmDevice &dev, benchmark_config_t &cfg);

  int runWmma(RocmDevice &dev, benchmark_config_t &cfg, Category category);
  int runRocwmma(RocmDevice &dev, benchmark_config_t &cfg, Category category);
  int runMfma(RocmDevice &dev, benchmark_config_t &cfg, Category category);
  int runSparseMfma(RocmDevice &dev, benchmark_config_t &cfg, Category category);
  int runRocblas(RocmDevice &dev, benchmark_config_t &cfg, Category category);
  int runHipblasLt(RocmDevice &dev, benchmark_config_t &cfg);
  int runGlobalBandwidth(RocmDevice &dev, benchmark_config_t &cfg);
  int runLocalBandwidth(RocmDevice &dev, benchmark_config_t &cfg);
  int runImageBandwidth(RocmDevice &dev, benchmark_config_t &cfg);
  int runTransferBandwidth(RocmDevice &dev, benchmark_config_t &cfg);

  int runKernelLatency(RocmDevice &dev, benchmark_config_t &cfg);

private:
  bool initialised;
  std::vector<int> devIndices;
  hipError_t m_initResult = hipSuccess;
  logger::DeviceScope *currentDeviceScope = nullptr;

  bool initRuntime();

  float runKernel(RocmDevice &dev, hipFunction_t fn,
                  uint32_t gridX, uint32_t blockX,
                  void **args,
                  unsigned int targetTimeUs, unsigned int forcedIters);

  int runComputeKernel(RocmDevice &dev, benchmark_config_t &cfg,
                       const rocm_compute_desc_t &d);
};

// Embedded HIP kernel code objects (hipcc-compiled at build time, generated
// into rocm_kernels_generated by EmbedRocmKernels.cmake).
namespace rocm_kernels {
  struct Blob {
    const unsigned char *data;   // code-object bundle bytes
    unsigned int         len;    // byte count
    const char          *name;   // file stem, e.g. "compute_sp.hip"
  };

  extern const Blob compute_sp;
  extern const Blob compute_hp;
  extern const Blob compute_dp;
  extern const Blob compute_mp;
  extern const Blob compute_bf16;
  extern const Blob compute_int32;
  extern const Blob compute_int8_dp;
  extern const Blob wmma_fp16;
  extern const Blob wmma_bf16;
  extern const Blob wmma_fp8;
  extern const Blob wmma_int8;
  extern const Blob rocwmma_fp16;
  extern const Blob rocwmma_int8;
  extern const Blob mfma_fp16;
  extern const Blob mfma_bf16;
  extern const Blob mfma_int8;
  extern const Blob mfma_fp8;
  extern const Blob mfma_mxfp4;
  extern const Blob smfmac_fp16;
  extern const Blob smfmac_bf16;
  extern const Blob smfmac_int8;
  extern const Blob smfmac_fp8;
  extern const Blob global_bandwidth;
  extern const Blob local_bandwidth;
  extern const Blob image_bandwidth;
  extern const Blob kernel_latency;
}

#endif // ENABLE_ROCM
#endif // ROCM_PEAK_H
