/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_clpeak_jni_connect */

#ifndef _Included_kr_clpeak_jni_connect
#define _Included_kr_clpeak_jni_connect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_connect
 * Method:    launchClpeak
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kr_clpeak_jni_1connect_launchClpeak
(JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif


#ifndef _Included_kr_clpeak_MainActivity
#define _Included_kr_clpeak_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_clpeak_MainActivity
 * Method:    setenv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_kr_clpeak_MainActivity_setenv
(JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
