# EmbedRocmKernels.cmake
#
# Embeds .hip source files into the binary as C++ raw-string-literal externs.
# HIPRTC compiles them at runtime, so the build never invokes hipcc and never
# emits an offline code object.

function(embed_rocm_kernels)
  cmake_parse_arguments(ER "" "TARGET" "KERNELS" ${ARGN})

  set(GEN_CPP "${CMAKE_CURRENT_BINARY_DIR}/rocm_kernels_generated.cpp")
  set(CPP_CONTENT "// Auto-generated by EmbedRocmKernels.cmake. Do not edit.\n")
  string(APPEND CPP_CONTENT "namespace rocm_kernels {\n\n")

  foreach(KERNEL ${ER_KERNELS})
    if(NOT EXISTS "${KERNEL}")
      message(FATAL_ERROR "embed_rocm_kernels: source not found: ${KERNEL}")
    endif()
    get_filename_component(KERNEL_NAME ${KERNEL} NAME_WE)
    set_property(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
      APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${KERNEL}")

    file(READ "${KERNEL}" KSRC)
    set(DELIM "K")
    string(APPEND CPP_CONTENT "// from ${KERNEL_NAME}.hip\n")
    string(APPEND CPP_CONTENT "const char *${KERNEL_NAME}_name = \"${KERNEL_NAME}.hip\";\n")
    string(APPEND CPP_CONTENT "const char *${KERNEL_NAME}_src = R\"${DELIM}(\n")
    string(APPEND CPP_CONTENT "${KSRC}")
    string(APPEND CPP_CONTENT ")${DELIM}\";\n\n")

    string(TOUPPER "${KERNEL_NAME}" KU)
    target_compile_definitions(${ER_TARGET} PRIVATE CLPEAK_ROCM_HAS_${KU})
  endforeach()

  string(APPEND CPP_CONTENT "} // namespace rocm_kernels\n")
  file(WRITE "${GEN_CPP}" "${CPP_CONTENT}")
  target_sources(${ER_TARGET} PRIVATE "${GEN_CPP}")
endfunction()
