# EmbedBin.cmake  --  run as `cmake -P` at build time.
#
# Reads a precompiled device binary (CUDA fatbin / HIP code object) and emits a
# C++ translation unit defining one `<NAMESPACE>::Blob` with the bytes inlined.
# Runs at build time (not configure time) because the binary is produced by a
# preceding custom command.
#
# Required -D args:
#   INPUT      path to the binary, or the literal NONE to emit an empty stub
#   OUTPUT     path of the .cpp to generate
#   SYMBOL     C++ identifier for the Blob (e.g. compute_sp)
#   SRCNAME    diagnostic name stored in the Blob (e.g. compute_sp.cu)
#   NAMESPACE  enclosing namespace (cuda_kernels / rocm_kernels)
#
# The Blob layout is duplicated verbatim from the backend's *_peak.h; keep the
# three members in sync.

set(_c "// Auto-generated by EmbedBin.cmake.  Do not edit.\n")
string(APPEND _c "namespace ${NAMESPACE} {\n")
string(APPEND _c "struct Blob { const unsigned char *data; unsigned int len; const char *name; };\n")

if(INPUT STREQUAL "NONE" OR NOT EXISTS "${INPUT}")
  # No arch the installed toolkit can target -> empty blob.  Loading it fails
  # gracefully at runtime (the host-side capability gate normally skips first).
  string(APPEND _c "extern const Blob ${SYMBOL} = { 0, 0u, \"${SRCNAME}\" };\n")
else()
  file(READ "${INPUT}" _hex HEX)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
  # wrap 16 bytes per line to stay well under compiler line-length limits.
  # CMake's regex has no {n} interval quantifier, so spell out 16 groups.
  string(REGEX REPLACE
    "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)"
    "\\1\n" _bytes "${_bytes}")
  string(APPEND _c "static const unsigned char ${SYMBOL}_data[] = {\n${_bytes}\n};\n")
  string(APPEND _c "extern const Blob ${SYMBOL} = { ${SYMBOL}_data, (unsigned int)sizeof(${SYMBOL}_data), \"${SRCNAME}\" };\n")
endif()

string(APPEND _c "} // namespace ${NAMESPACE}\n")
file(WRITE "${OUTPUT}" "${_c}")
