
set(VERSION_MAJOR 1)
set(VERSION_MINOR 1)
set(VERSION_PATCH 2)
set(VERSION_SUFFIX "")
set(VERSION_STR "${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}${VERSION_SUFFIX}")

add_definitions("-DVERSION_STR=\"${VERSION_STR}\"")
