# EmbedCudaKernels.cmake
#
# Embeds .cu source files into the binary as C++ raw-string-literal externs.
# NVRTC compiles them at runtime, so the build never invokes nvcc and never
# emits PTX/cubin/fatbin.  Mirrors the spirit of CompileShaders.cmake but
# trivially simpler -- there is no offline compile step.
#
# Usage:
#   embed_cuda_kernels(TARGET <target> KERNELS <a.cu> <b.cu> ...)
# Generates ${CMAKE_CURRENT_BINARY_DIR}/cuda_kernels_generated.cpp with one
# `extern const char *<name>_src;` and `<name>_name;` per kernel, in the
# cuda_kernels namespace declared in include/cuda_peak.h.
#
# Defines CLPEAK_CUDA_HAS_<NAME> on the target so per-kernel host code can
# be conditionally compiled (matching the CompileShaders.cmake convention).

function(embed_cuda_kernels)
  cmake_parse_arguments(EC "" "TARGET" "KERNELS" ${ARGN})

  set(GEN_CPP "${CMAKE_CURRENT_BINARY_DIR}/cuda_kernels_generated.cpp")
  set(CPP_CONTENT "// Auto-generated by EmbedCudaKernels.cmake.  Do not edit.\n")
  string(APPEND CPP_CONTENT "namespace cuda_kernels {\n\n")

  foreach(KERNEL ${EC_KERNELS})
    if(NOT EXISTS "${KERNEL}")
      message(FATAL_ERROR "embed_cuda_kernels: source not found: ${KERNEL}")
    endif()
    get_filename_component(KERNEL_NAME ${KERNEL} NAME_WE)
    set_property(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
      APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${KERNEL}")

    file(READ "${KERNEL}" KSRC)
    # Pick a delimiter that cannot collide with any sequence inside the .cu
    # source.  CLPEAK_KDELIM is unlikely to appear in CUDA code.
    set(DELIM "CLPEAK_KDELIM")
    string(APPEND CPP_CONTENT "// from ${KERNEL_NAME}.cu\n")
    # See EmbedMetalKernels.cmake -- no `extern` to keep clang happy.
    string(APPEND CPP_CONTENT "const char *${KERNEL_NAME}_name = \"${KERNEL_NAME}.cu\";\n")
    string(APPEND CPP_CONTENT "const char *${KERNEL_NAME}_src = R\"${DELIM}(\n")
    string(APPEND CPP_CONTENT "${KSRC}")
    string(APPEND CPP_CONTENT ")${DELIM}\";\n\n")

    string(TOUPPER "${KERNEL_NAME}" KU)
    target_compile_definitions(${EC_TARGET} PRIVATE CLPEAK_CUDA_HAS_${KU})
  endforeach()

  string(APPEND CPP_CONTENT "} // namespace cuda_kernels\n")
  file(WRITE "${GEN_CPP}" "${CPP_CONTENT}")
  target_sources(${EC_TARGET} PRIVATE "${GEN_CPP}")
endfunction()
