/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_clpeak_jni_connect */

#ifndef _Included_kr_clpeak_jni_connect
#define _Included_kr_clpeak_jni_connect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_connect
 * Method:    launchClpeak
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kr_clpeak_jni_1connect_launchClpeak
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
